#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

echo -e "Updating and installing Nginx.\n"
apt-get update -y -qq && \
    apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
service nginx start

# Allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

# Backup default index
if [ -f /var/www/html/index.nginx-debian.html ]; then
    cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
else
    echo "Default index file not found. Skipping backup."
fi

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
service nginx restart

echo -e "\nCompleted. ✅\n"
